### PR TITLE
fix unable to preventDefault inside passive error

### PR DESCRIPTION
**Pull request by nuintun**
Unable to preventDefault inside passive event listener invocation

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28787

**Comment by yoyo837** [comment]
直接删了怕是不行吧？给容器加`touch-action: none`来的快些。

**Comment by jljsj33** [comment]
是跑用例用的，，如果有问题就直接删了。。。没关系

**Comment by samuelcastro** [comment]
Hi @afc163, I'm still having this same issue. Have you released it?

**Comment by Shahzaibmalik55** [comment]
I am still facing this issue is this resolve yet ?

**Pull request merged**
