### PR TITLE
feat: add autoFocus props for drawer

### LINKED ISSUE #28097: Drawer autoFocus
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When drawer opens, focusing on the element generates unexpected and/or unwanted UI behaviour. Specially if Drawer is positioned absolute in a specific container.

### What does the proposed API look like?
Have a prop to disable autoFocus when drawer opens:
`autoFocus={false}`

```
<Drawer
  visible={this.state.visible}
  getContainer="#drawer-container-selector"
  style={{ position: "absolute" }}
  autoFocus={false}
>
  <p>Drawer Content</p>
</Drawer>
```

### PR DESCRIPTION
**Pull request by baxtergu**
close [ant-design/ant-design#28787](https://github.com/ant-design/ant-design/issues/28097)

### CODE REVIEW

**Comment by baxtergu** [comment]
Ready for review

**Comment by baxtergu** [comment]
@afc163 @zombieJ

**Review by xrkffgg — APPROVED** [review]

**Comment by vayyala** [comment]
Anything blocking merging this? Thanks!

@xrkffgg

**Review by kerm1it — APPROVED** [review]

**Comment by kerm1it** [comment]
@afc163 publish minor version.

**Comment by afc163** [comment]
done

**Pull request merged**
