### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by chenshuai2144**
- [x] use storybook
- [x] use typescript 
- [x] merge master

### CODE REVIEW

**Comment by martin-braun** [comment]
Hi, 

thanks for attempting to bring Typescript support to this lib. I really would like to use rc-drawer with typings. Any information when this will be available on npm?

**Comment by jljsj33** [comment]
可以合了不？？？ @chenshuai2144 ，，好了我就发个版本了。。

**Comment by afc163** [comment]
ci 都挂了

**Comment by jljsj33** [comment]
我说他的功能都一样了没，， ci 我在看,,, 为什么会都了一个 style ？？？

**Comment by jljsj33** [comment]
操蛋，，

**Comment by jljsj33** [comment]
https://github.com/react-component/drawer/pull/110

**Pull request closed without merging**
