### PR TITLE
fix: startPos may be undefined

### LINKED ISSUE #193: undefined is not an object (evaluating 'n.startPos.x')
image

### LINKED ISSUE #13745: Drawer inside drawer crashes on mobile devices when scrolling is attempted
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Touch devices. Tested in Safari on iOS and Chrome developer tools

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/rlw6om62xo)

### Steps to reproduce
1. Open a drawer from inside a drawer
2. Try to scroll such beyond the start of the page

### What is expected?
Nothing

### What is actually happening?
Exception:

```
Uncaught TypeError: currentTarget.scrollTo is not a function
    at Drawer.getTouchParentScroll (Drawer.js:582)
    at Drawer.getTouchParentScroll (Drawer.js:588)
    at Drawer.getTouchParentScroll (Drawer.js:588)
    at Drawer.getTouchParentScroll (Drawer.js:588)
    at Drawer.getTouchParentScroll (Drawer.js:588)
    at Drawer.getTouchParentScroll (Drawer.js:588)
    at Drawer.getTouchParentScroll (Drawer.js:588)
    at Drawer.getTouchParentScroll (Drawer.js:588)
    at Drawer.getTouchParentScroll (Drawer.js:588)
    at Drawer.getTouchParentScroll (Drawer.js:588)
    at removeMoveHandler (Drawer.js:610)
```

### LINKED ISSUE #25870: Error when dragging slider on the last drawerChild in mobile screen - DrawerChild._this.removeMoveHandler
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/dreamy-pine-js7yd)

### Steps to reproduce
- open reproduction link, open link in new tab.
- inspect the browser and choose a mobile device.
- reload the page.
- open the first drawer, open the childDrawer.
- Drag the slider.

### What is expected?
There are no errors when dragging the slider on childDrawer

### What is actually happening?
When on the mobile screen size and dragging the slider in childDrawer the error "Cannot read property 'x' of undefined, DrawerChild._this.removeMoveHandler" appears. This error will only appear when on the mobile screen size and only in the childDrawer or in the last Multi-level drawer.
*dragging only

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.13.1 |
| System | Mac |
| Browser | Chrome |

### LINKED ISSUE #29794: TypeError undefined is not an object (evaluating 'r.startPos.x')
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/drawerdemo-z66dd)

### Steps to reproduce
TypeError undefined is not an object (evaluating 'r.startPos.x') 
    ../node_modules/rc-drawer/es/DrawerChild.js:176 
    ../node_modules/@bugsnag/browser/dist/bugsnag.js:2709 

### What is expected?
no crash

### What is actually happening?
only some users crash

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 16.14.0 |
| System | ios 14.x |
| Browser | Mobile Safari UI/WKWebView |

---
TypeError undefined is not an object (evaluating 'r.startPos.x') 
    ../node_modules/rc-drawer/es/DrawerChild.js:176 
    ../node_modules/@bugsnag/browser/dist/bugsnag.js:2709

### LINKED ISSUE #32904: [Bug] Slider在触摸屏下大量报错
### 重现链接

https://codesandbox.io/s/antd-reproduction-template-forked-cp6uy

### antd 版本

4.17.0

### 重现步骤

1. 使用Chrome访问 https://cp6uy.csb.app/
2. 打开开发者工具
3. 切换 iPhone 模拟
4. 拖动Slider
5. 控制台报大量错误卡死

### 期望的结果是什么？

不报错

### 实际的结果是什么？

大量报错导致性能下降

### 浏览器

Chrome

### 浏览器版本

_No response_

### 操作系统

Windows

### PR DESCRIPTION
**Pull request by mufengfang**
close https://github.com/react-component/drawer/issues/193
close https://github.com/ant-design/ant-design/issues/32904
close https://github.com/ant-design/ant-design/issues/29794
close https://github.com/ant-design/ant-design/issues/13745
close https://github.com/ant-design/ant-design/issues/25870

### CODE REVIEW

**Comment by afc163** [comment]
Could you add test case for this?

**Comment by mufengfang** [comment]
> Could you add test case for this?

OK，I will have a look.

**Comment by mufengfang** [comment]
> Could you add test case for this?

I've finished it，bother you to approve the coverage test workflow again.

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
close https://github.com/ant-design/ant-design/issues/32904

**Pull request merged**
